### ISSUE TITLE
cloned project has build errors

### ISSUE THREAD

**Issue by epgeroy** [CodinGame/game-tictactoe#2]
`Error:(47, 21) java: cannot find symbol
  symbol:   method setBaseHeight(int)
  location: class com.codingame.gameengine.module.entities.Sprite`

any ideas here, just trying to start

also comented the lines 

`                    .setBaseHeight(116)
                    .setBaseWidth(116);`

from `Referee.java` and compiles, but the http://localhost:8888/test.html throws a 404 error

thxs

**Comment by CGjupoulton** [comment]
Fixed by https://github.com/CodinGame/game-tictactoe/pull/3
